import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { STANDARD_OBJECTS } from 'twenty-shared/metadata';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT } from 'src/engine/metadata-modules/object-metadata/constants/standard-relation-field-properties.constant';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildIssueStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'issue', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'issue'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Issue record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Issue-specific fields
  title: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'title',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Title`),
      description: i18nLabel(msg`Issue title`),
      icon: 'IconNotes',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  issueKey: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'issueKey',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Key`),
      description: i18nLabel(
        msg`Issue key, auto-generated from the project key`,
      ),
      icon: 'IconKey',
      isNullable: true,
      isUnique: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  description: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'description',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Description`),
      description: i18nLabel(msg`Issue description`),
      icon: 'IconFilePencil',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  issueType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'issueType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Issue type`),
      description: i18nLabel(msg`Issue type`),
      icon: 'IconTag',
      isNullable: true,
      defaultValue: "'TASK'",
      options: [
        {
          id: 'a818e3d2-043f-4b33-99aa-759b0423c739',
          value: 'STORY',
          label: i18nLabel(msg`Story`),
          position: 0,
          color: 'green',
        },
        {
          id: '5f556d51-5a2b-4c19-9e0d-5f4f5c4f5f92',
          value: 'TASK',
          label: i18nLabel(msg`Task`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'd6a5095b-9292-4200-abff-ff9f55bc56de',
          value: 'BUG',
          label: i18nLabel(msg`Bug`),
          position: 2,
          color: 'red',
        },
        {
          id: '6a2ed5d7-0b68-4d42-8181-eb2eae147607',
          value: 'SUBTASK',
          label: i18nLabel(msg`Subtask`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  priority: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'priority',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Priority`),
      description: i18nLabel(msg`Issue priority`),
      icon: 'IconFlag',
      isNullable: true,
      defaultValue: "'MEDIUM'",
      options: [
        {
          id: '7a3ac4b4-1f11-4ef1-95eb-ee0c52e6898c',
          value: 'LOWEST',
          label: i18nLabel(msg`Lowest`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'e16557cb-f517-432f-86ee-be1af39501ba',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'ce1bb9a6-df3d-48a9-b1c2-ca172a288255',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 2,
          color: 'yellow',
        },
        {
          id: '8e220276-11d4-4a12-a62b-dd9df11815f4',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 3,
          color: 'orange',
        },
        {
          id: '0ef26535-456b-4568-baa3-8afd630dacc4',
          value: 'HIGHEST',
          label: i18nLabel(msg`Highest`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolution: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolution',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Resolution`),
      description: i18nLabel(msg`Issue resolution`),
      icon: 'IconCircleCheck',
      isNullable: true,
      options: [
        {
          id: 'c363ead2-e423-4375-9fe4-0b0dedd6c72d',
          value: 'DONE',
          label: i18nLabel(msg`Done`),
          position: 0,
          color: 'green',
        },
        {
          id: '7822f7d8-b81c-417f-a11a-58bac696377c',
          value: 'WONT_DO',
          label: i18nLabel(msg`Won't Do`),
          position: 1,
          color: 'gray',
        },
        {
          id: '0a12e51d-b23d-41df-a313-7c3059d8cad5',
          value: 'DUPLICATE',
          label: i18nLabel(msg`Duplicate`),
          position: 2,
          color: 'orange',
        },
        {
          id: '0b2ccfe7-7544-4585-9b8e-62e6af8f7bea',
          value: 'CANNOT_REPRODUCE',
          label: i18nLabel(msg`Cannot Reproduce`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  storyPoints: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'storyPoints',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Story points`),
      description: i18nLabel(msg`Story points estimate`),
      icon: 'IconNumber',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  labels: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'labels',
      type: FieldMetadataType.MULTI_SELECT,
      label: i18nLabel(msg`Labels`),
      description: i18nLabel(msg`Issue labels`),
      icon: 'IconTags',
      isNullable: true,
      options: [
        {
          id: '79b31c21-da77-4ffe-8b44-ac02e9d3e4ce',
          value: 'BUG',
          label: i18nLabel(msg`Bug`),
          position: 0,
          color: 'red',
        },
        {
          id: '4bf90866-9ea1-4ce0-b6e8-727e7894eb99',
          value: 'ENHANCEMENT',
          label: i18nLabel(msg`Enhancement`),
          position: 1,
          color: 'blue',
        },
        {
          id: '8a18d617-df0c-4ecc-9a89-c5124dd652b1',
          value: 'DOCUMENTATION',
          label: i18nLabel(msg`Documentation`),
          position: 2,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  dueDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dueDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Due date`),
      description: i18nLabel(msg`Issue due date`),
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  originalEstimateMinutes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'originalEstimateMinutes',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Original estimate (minutes)`),
      description: i18nLabel(msg`Original time estimate in minutes`),
      icon: 'IconClock',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  remainingEstimateMinutes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'remainingEstimateMinutes',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Remaining estimate (minutes)`),
      description: i18nLabel(msg`Remaining time estimate in minutes`),
      icon: 'IconClockHour4',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timeSpentMinutes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'timeSpentMinutes',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Time spent (minutes)`),
      description: i18nLabel(msg`Total time logged in minutes`),
      icon: 'IconClockPlay',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  assignee: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assignee',
      label: i18nLabel(msg`Assignee`),
      description: i18nLabel(msg`Issue assignee`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'assignedIssues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'assigneeId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reporter: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'reporter',
      label: i18nLabel(msg`Reporter`),
      description: i18nLabel(msg`Issue reporter`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'reportedIssues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'reporterId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  merchants: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'merchants',
      label: i18nLabel(msg`Merchants`),
      description: i18nLabel(msg`Merchants linked to this issue`),
      icon: 'IconBuildingStore',
      isNullable: true,
      targetObjectName: 'issueMerchant',
      targetFieldName: 'issue',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
      junctionTargetFieldUniversalIdentifier:
        STANDARD_OBJECTS.issueMerchant.fields.merchant.universalIdentifier,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  project: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'project',
      label: i18nLabel(msg`Project`),
      description: i18nLabel(msg`Issue's project`),
      icon: 'IconListDetails',
      isNullable: false,
      targetObjectName: 'project',
      targetFieldName: 'issues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'projectId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'status',
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Issue status`),
      icon: 'IconProgressCheck',
      isNullable: true,
      targetObjectName: 'issueStatus',
      targetFieldName: 'issues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'statusId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sprint: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'sprint',
      label: i18nLabel(msg`Sprint`),
      description: i18nLabel(msg`Issue's sprint (null = backlog)`),
      icon: 'IconRun',
      isNullable: true,
      targetObjectName: 'sprint',
      targetFieldName: 'issues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'sprintId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  epic: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'epic',
      label: i18nLabel(msg`Epic`),
      description: i18nLabel(msg`Issue's epic`),
      icon: 'IconStack2',
      isNullable: true,
      targetObjectName: 'epic',
      targetFieldName: 'issues',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'epicId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  parent: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'parent',
      label: i18nLabel(msg`Parent issue`),
      description: i18nLabel(
        msg`Parent issue (epic link for a story, story for a subtask)`,
      ),
      icon: 'IconArrowUpRight',
      isNullable: true,
      targetObjectName: 'issue',
      targetFieldName: 'children',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'parentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  children: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'children',
      label: i18nLabel(msg`Child issues`),
      description: i18nLabel(msg`Child issues (stories or subtasks)`),
      icon: 'IconSitemap',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'issue',
      targetFieldName: 'parent',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  issueComments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'issueComments',
      label: i18nLabel(msg`Comments`),
      description: i18nLabel(msg`Issue's comments`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'issueComment',
      targetFieldName: 'issue',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  worklogs: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'worklogs',
      label: i18nLabel(msg`Worklogs`),
      description: i18nLabel(msg`Issue's worklogs`),
      icon: 'IconClock',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'worklog',
      targetFieldName: 'issue',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      isSystemSideEffect: true,
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment.label,
      ),
      description: i18nLabel(msg`Issue attachments`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment
        .icon,
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetIssue',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      isSystemSideEffect: true,
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity
          .label,
      ),
      description: i18nLabel(msg`Timeline Activities linked to the issue`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT
        .timelineActivity.icon,
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetIssue',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
