import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildIssueStatusStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'issueStatus', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'issueStatus'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // IssueStatus-specific fields
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Issue status record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Issue status name`),
      icon: 'IconTag',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Options are Twenty's full theme color palette (see MAIN_COLORS_LIGHT in
  // twenty-ui) so the value always maps to a real color swatch — a free-text
  // field let users type anything, which the badge display couldn't render.
  // Option `value`s must be SCREAMING_SNAKE_CASE (enforced by
  // validateMetadataOptionValue/isSnakeCaseString), so they're the uppercase
  // form of each ThemeColor key — DEFAULT_ISSUE_STATUSES
  // (project-post-query-hook.service.ts) writes these same uppercase values.
  // `color` on each option (the swatch shown for the option itself) stays
  // the lowercase ThemeColor key.
  color: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'color',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Color`),
      description: i18nLabel(msg`Issue status color`),
      icon: 'IconColorSwatch',
      isNullable: true,
      options: [
        {
          id: 'c58d9621-306f-4b97-bc23-1953b96ede78',
          value: 'RED',
          label: i18nLabel(msg`Red`),
          position: 0,
          color: 'red',
        },
        {
          id: '40b29386-f3c2-4043-8c6b-263257409d10',
          value: 'RUBY',
          label: i18nLabel(msg`Ruby`),
          position: 1,
          color: 'ruby',
        },
        {
          id: '1999c56d-3f54-4b70-a2d2-4bd3b70a6a5c',
          value: 'CRIMSON',
          label: i18nLabel(msg`Crimson`),
          position: 2,
          color: 'crimson',
        },
        {
          id: 'ea827e92-5a15-4583-9253-f7e318593a53',
          value: 'TOMATO',
          label: i18nLabel(msg`Tomato`),
          position: 3,
          color: 'tomato',
        },
        {
          id: '88f6f538-dac2-4d68-bb7e-edda0a943b75',
          value: 'ORANGE',
          label: i18nLabel(msg`Orange`),
          position: 4,
          color: 'orange',
        },
        {
          id: '87379269-f4e1-443f-a1a1-54db6599bb68',
          value: 'AMBER',
          label: i18nLabel(msg`Amber`),
          position: 5,
          color: 'amber',
        },
        {
          id: '41d3af2b-345b-4d6e-b35d-50836ad8eebf',
          value: 'YELLOW',
          label: i18nLabel(msg`Yellow`),
          position: 6,
          color: 'yellow',
        },
        {
          id: '9e848c54-58fb-42e6-ac29-14a97356148d',
          value: 'LIME',
          label: i18nLabel(msg`Lime`),
          position: 7,
          color: 'lime',
        },
        {
          id: '86c9ab62-38ff-4588-8fc1-119e174dc66f',
          value: 'GRASS',
          label: i18nLabel(msg`Grass`),
          position: 8,
          color: 'grass',
        },
        {
          id: '6175fa96-2fa9-46e6-922b-dc41db4ffe98',
          value: 'GREEN',
          label: i18nLabel(msg`Green`),
          position: 9,
          color: 'green',
        },
        {
          id: '143f26cd-f978-4f24-b237-55974568c08a',
          value: 'JADE',
          label: i18nLabel(msg`Jade`),
          position: 10,
          color: 'jade',
        },
        {
          id: '3382adab-ea5f-4c9c-b714-5971a2fc35e2',
          value: 'MINT',
          label: i18nLabel(msg`Mint`),
          position: 11,
          color: 'mint',
        },
        {
          id: 'a13e4227-3b6b-4bf9-a1c8-af904a38fc73',
          value: 'TURQUOISE',
          label: i18nLabel(msg`Turquoise`),
          position: 12,
          color: 'turquoise',
        },
        {
          id: 'a1e57cf8-defa-4266-8931-9642307d327a',
          value: 'CYAN',
          label: i18nLabel(msg`Cyan`),
          position: 13,
          color: 'cyan',
        },
        {
          id: 'ab98b764-bcf7-4a41-b7ea-efe592fbc259',
          value: 'SKY',
          label: i18nLabel(msg`Sky`),
          position: 14,
          color: 'sky',
        },
        {
          id: 'fec08216-eabf-42a0-8891-9fcc7fdf2773',
          value: 'BLUE',
          label: i18nLabel(msg`Blue`),
          position: 15,
          color: 'blue',
        },
        {
          id: 'ac841f37-8a61-4ada-b19c-11cb420c9873',
          value: 'IRIS',
          label: i18nLabel(msg`Iris`),
          position: 16,
          color: 'iris',
        },
        {
          id: 'd1b65202-7c31-4642-b627-2305c7c1d13f',
          value: 'VIOLET',
          label: i18nLabel(msg`Violet`),
          position: 17,
          color: 'violet',
        },
        {
          id: '64c9651e-00e8-4dd9-89cf-867ea43c5e35',
          value: 'PURPLE',
          label: i18nLabel(msg`Purple`),
          position: 18,
          color: 'purple',
        },
        {
          id: '352e03e9-b8b7-4c80-a3af-2047df14df2b',
          value: 'PLUM',
          label: i18nLabel(msg`Plum`),
          position: 19,
          color: 'plum',
        },
        {
          id: '2f878330-2773-4395-b2df-53ad2e8e5d6d',
          value: 'PINK',
          label: i18nLabel(msg`Pink`),
          position: 20,
          color: 'pink',
        },
        {
          id: 'ccec9af4-50bb-47de-822d-c1c606c5e2a0',
          value: 'BRONZE',
          label: i18nLabel(msg`Bronze`),
          position: 21,
          color: 'bronze',
        },
        {
          id: 'b45733be-9fb8-4719-ae40-14434e72e99d',
          value: 'GOLD',
          label: i18nLabel(msg`Gold`),
          position: 22,
          color: 'gold',
        },
        {
          id: 'f2e8891d-a629-4d6e-b9a5-5bc00ec0d36b',
          value: 'BROWN',
          label: i18nLabel(msg`Brown`),
          position: 23,
          color: 'brown',
        },
        {
          id: '29ff6bf5-29e5-4f07-99e3-88c27e0fc990',
          value: 'GRAY',
          label: i18nLabel(msg`Gray`),
          position: 24,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  category: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'category',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Category`),
      description: i18nLabel(
        msg`Status category, used to compute progress and roadmap grouping`,
      ),
      icon: 'IconProgressCheck',
      isNullable: true,
      options: [
        {
          id: '0d4fc734-27a9-4837-ac32-0327385a690f',
          value: 'UNSTARTED',
          label: i18nLabel(msg`Unstarted`),
          position: 0,
          color: 'gray',
        },
        {
          id: '195a9e79-68b9-42b2-aa76-f9c39cfc6f27',
          value: 'STARTED',
          label: i18nLabel(msg`Started`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '689ec945-621f-489b-aa88-144572ade801',
          value: 'DONE',
          label: i18nLabel(msg`Done`),
          position: 2,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  project: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'project',
      label: i18nLabel(msg`Project`),
      description: i18nLabel(msg`Project this status belongs to`),
      icon: 'IconListDetails',
      isNullable: false,
      targetObjectName: 'project',
      targetFieldName: 'issueStatuses',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'projectId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  issues: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'issues',
      label: i18nLabel(msg`Issues`),
      description: i18nLabel(msg`Issues currently in this status`),
      icon: 'IconLayoutKanban',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'issue',
      targetFieldName: 'status',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
