import { defineObject, FieldType } from 'twenty-sdk/define';

import { CANCEL_CATEGORY_OPTIONS } from '../constants/cancel-category-options';
import { SHIFT_STATUS_OPTIONS } from '../constants/shift-status-options';
import {
  SHIFT_CANCEL_CATEGORY_FIELD_UID,
  SHIFT_CANCEL_REASON_FIELD_UID,
  SHIFT_CANCELLED_AT_FIELD_UID,
  SHIFT_CHECK_IN_AT_FIELD_UID,
  SHIFT_CHECK_IN_LATE_MINUTES_FIELD_UID,
  SHIFT_CHECK_OUT_AT_FIELD_UID,
  SHIFT_DATE_FIELD_UID,
  SHIFT_END_TIME_FIELD_UID,
  SHIFT_HANDOVER_NOTE_FIELD_UID,
  SHIFT_NAME_FIELD_UID,
  SHIFT_OBJECT_UID,
  SHIFT_RATE_MULTIPLIER_FIELD_UID,
  SHIFT_START_TIME_FIELD_UID,
  SHIFT_STATUS_FIELD_UID,
  SHIFT_TEMPLATE_CODE_SNAPSHOT_FIELD_UID,
  SHIFT_TEMPLATE_NAME_SNAPSHOT_FIELD_UID,
  SHIFT_WORKING_MINUTES_FIELD_UID,
} from '../constants/universal-identifiers';

// The template snapshot fields (templateCode/templateName/startTime/endTime)
// are frozen at registration on purpose: archiving or editing a template must
// never rewrite the history of shifts already worked.
export default defineObject({
  universalIdentifier: SHIFT_OBJECT_UID,
  nameSingular: 'shift',
  namePlural: 'shifts',
  labelSingular: 'Shift',
  labelPlural: 'Shifts',
  description:
    "One member's registration + attendance for one shift template on one date",
  icon: 'IconCalendarClock',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: SHIFT_NAME_FIELD_UID,
  fields: [
    {
      universalIdentifier: SHIFT_NAME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Auto-generated "<code> <date>"',
      icon: 'IconAbc',
      isNullable: false,
      defaultValue: "''",
      isSearchable: true,
    },
    {
      universalIdentifier: SHIFT_DATE_FIELD_UID,
      type: FieldType.TEXT,
      name: 'date',
      label: 'Date',
      description: 'YYYY-MM-DD, ICT',
      icon: 'IconCalendarEvent',
      isNullable: false,
      defaultValue: "''",
    },
    {
      universalIdentifier: SHIFT_STATUS_FIELD_UID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Shift lifecycle status',
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'UPCOMING'",
      options: [...SHIFT_STATUS_OPTIONS],
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_CODE_SNAPSHOT_FIELD_UID,
      type: FieldType.TEXT,
      name: 'templateCode',
      label: 'Template code',
      description:
        'Snapshot of the template code, survives template archive/rename',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_NAME_SNAPSHOT_FIELD_UID,
      type: FieldType.TEXT,
      name: 'templateName',
      label: 'Template name',
      description: 'Snapshot of the template name',
      icon: 'IconAbc',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_START_TIME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'startTime',
      label: 'Start time',
      description: 'Snapshot of the template start time, HH:mm',
      icon: 'IconClockPlay',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_END_TIME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'endTime',
      label: 'End time',
      description: 'Snapshot of the template end time, HH:mm',
      icon: 'IconClockStop',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_CHECK_IN_AT_FIELD_UID,
      type: FieldType.DATE_TIME,
      name: 'checkInAt',
      label: 'Checked in at',
      description: 'When the member checked in',
      icon: 'IconLogin',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_CHECK_OUT_AT_FIELD_UID,
      type: FieldType.DATE_TIME,
      name: 'checkOutAt',
      label: 'Checked out at',
      description: 'When the member checked out',
      icon: 'IconLogout',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_CHECK_IN_LATE_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'checkInLateMinutes',
      label: 'Check-in late (minutes)',
      description: 'Empty = on time; >=1 = minutes past shift start (no grace)',
      icon: 'IconAlarmSnooze',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_WORKING_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'workingMinutes',
      label: 'Working minutes',
      description: 'Payable minutes, frozen at check-out',
      icon: 'IconClockHour4',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_RATE_MULTIPLIER_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'rateMultiplier',
      label: 'Rate multiplier',
      description: 'Empty = 1.0; stamped from special days at registration',
      icon: 'IconPercentage',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_HANDOVER_NOTE_FIELD_UID,
      type: FieldType.TEXT,
      name: 'handoverNote',
      label: 'Handover note',
      description: 'Pending conversations noted at check-out',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_CANCEL_REASON_FIELD_UID,
      type: FieldType.TEXT,
      name: 'cancelReason',
      label: 'Cancel reason',
      description: 'Why the shift was cancelled',
      icon: 'IconMessageCircleOff',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_CANCEL_CATEGORY_FIELD_UID,
      type: FieldType.SELECT,
      name: 'cancelCategory',
      label: 'Cancel category',
      description: 'Cancellation category',
      icon: 'IconTag',
      isNullable: true,
      options: [...CANCEL_CATEGORY_OPTIONS],
    },
    {
      universalIdentifier: SHIFT_CANCELLED_AT_FIELD_UID,
      type: FieldType.DATE_TIME,
      name: 'cancelledAt',
      label: 'Cancelled at',
      description: 'When the shift was cancelled',
      icon: 'IconCalendarX',
      isNullable: true,
    },
  ],
});
