import { defineObject, FieldType } from 'twenty-sdk/define';

import { DAY_KIND_OPTIONS } from '../constants/day-kind-options';
import {
  SHIFT_TEMPLATE_CODE_FIELD_UID,
  SHIFT_TEMPLATE_COLOR_FIELD_UID,
  SHIFT_TEMPLATE_DAY_KIND_FIELD_UID,
  SHIFT_TEMPLATE_DESCRIPTION_FIELD_UID,
  SHIFT_TEMPLATE_EARLY_CHECK_IN_MINUTES_FIELD_UID,
  SHIFT_TEMPLATE_END_TIME_FIELD_UID,
  SHIFT_TEMPLATE_IS_ACTIVE_FIELD_UID,
  SHIFT_TEMPLATE_LATE_CHECK_OUT_MINUTES_FIELD_UID,
  SHIFT_TEMPLATE_NAME_FIELD_UID,
  SHIFT_TEMPLATE_OBJECT_UID,
  SHIFT_TEMPLATE_SALARY_PER_HOUR_FIELD_UID,
  SHIFT_TEMPLATE_START_TIME_FIELD_UID,
} from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SHIFT_TEMPLATE_OBJECT_UID,
  nameSingular: 'shiftTemplate',
  namePlural: 'shiftTemplates',
  labelSingular: 'Shift Template',
  labelPlural: 'Shift Templates',
  description: 'A reusable shift definition (code, time window, OT kind)',
  icon: 'IconClockCog',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    SHIFT_TEMPLATE_NAME_FIELD_UID,
  fields: [
    {
      universalIdentifier: SHIFT_TEMPLATE_NAME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Shift display name',
      icon: 'IconAbc',
      isNullable: false,
      defaultValue: "''",
      isSearchable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_CODE_FIELD_UID,
      type: FieldType.TEXT,
      name: 'code',
      label: 'Code',
      description: 'Short shift code, e.g. SAE-TT-D',
      icon: 'IconHash',
      isNullable: false,
      defaultValue: "''",
      isSearchable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_START_TIME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'startTime',
      label: 'Start time',
      description: 'HH:mm, ICT',
      icon: 'IconClockPlay',
      isNullable: false,
      defaultValue: "''",
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_END_TIME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'endTime',
      label: 'End time',
      description: 'HH:mm, ICT — 24:00 allowed',
      icon: 'IconClockStop',
      isNullable: false,
      defaultValue: "''",
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_DAY_KIND_FIELD_UID,
      type: FieldType.SELECT,
      name: 'dayKind',
      label: 'Day kind',
      description: 'Weekday, weekend or holiday OT',
      icon: 'IconCalendarWeek',
      isNullable: true,
      options: [...DAY_KIND_OPTIONS],
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_EARLY_CHECK_IN_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'earlyCheckInMinutes',
      label: 'Early check-in (minutes)',
      description:
        'Check-in opens this many minutes before start. Empty = no guard',
      icon: 'IconClockUp',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_LATE_CHECK_OUT_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'lateCheckOutMinutes',
      label: 'Late check-out grace (minutes)',
      description: 'Payable minutes cap grace after end. Empty = cap disabled',
      icon: 'IconClockDown',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_SALARY_PER_HOUR_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'salaryPerHour',
      label: 'Salary per hour',
      description:
        'VND per hour, optional. Hidden from the catalog view; members see it only through their own report',
      icon: 'IconCurrencyDong',
      isNullable: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_COLOR_FIELD_UID,
      type: FieldType.TEXT,
      name: 'color',
      label: 'Color',
      description: 'Calendar badge color',
      icon: 'IconPalette',
      isNullable: true,
      defaultValue: "'#94a3b8'",
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_IS_ACTIVE_FIELD_UID,
      type: FieldType.BOOLEAN,
      name: 'isActive',
      label: 'Active',
      description: 'Inactive templates cannot be registered',
      icon: 'IconToggleRight',
      isNullable: false,
      defaultValue: true,
    },
    {
      universalIdentifier: SHIFT_TEMPLATE_DESCRIPTION_FIELD_UID,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      description: 'Description',
      icon: 'IconFileDescription',
      isNullable: true,
    },
  ],
});
