import { defineObject, FieldType } from 'twenty-sdk/define';

import { SPECIAL_DAY_KIND_OPTIONS } from '../constants/special-day-kind-options';
import {
  SPECIAL_DAY_DATE_FIELD_UID,
  SPECIAL_DAY_DAY_FIELD_UID,
  SPECIAL_DAY_IS_ACTIVE_FIELD_UID,
  SPECIAL_DAY_KIND_FIELD_UID,
  SPECIAL_DAY_MONTH_FIELD_UID,
  SPECIAL_DAY_MULTIPLIER_FIELD_UID,
  SPECIAL_DAY_NAME_FIELD_UID,
  SPECIAL_DAY_OBJECT_UID,
} from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SPECIAL_DAY_OBJECT_UID,
  nameSingular: 'specialDay',
  namePlural: 'specialDays',
  labelSingular: 'Special Day',
  labelPlural: 'Special Days',
  description: 'A holiday or special date with an OT pay multiplier',
  icon: 'IconCalendarStar',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: SPECIAL_DAY_NAME_FIELD_UID,
  fields: [
    {
      universalIdentifier: SPECIAL_DAY_NAME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Special day display name',
      icon: 'IconAbc',
      isNullable: false,
      defaultValue: "''",
      isSearchable: true,
    },
    {
      universalIdentifier: SPECIAL_DAY_KIND_FIELD_UID,
      type: FieldType.SELECT,
      name: 'kind',
      label: 'Kind',
      description: 'Repeats yearly or applies to one specific date',
      icon: 'IconRepeat',
      isNullable: false,
      defaultValue: "'YEARLY'",
      options: [...SPECIAL_DAY_KIND_OPTIONS],
    },
    {
      universalIdentifier: SPECIAL_DAY_MONTH_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'month',
      label: 'Month',
      description: '1-12, used when kind is Yearly',
      icon: 'IconCalendarMonth',
      isNullable: true,
    },
    {
      universalIdentifier: SPECIAL_DAY_DAY_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'day',
      label: 'Day',
      description: '1-31, used when kind is Yearly',
      icon: 'IconCalendarDue',
      isNullable: true,
    },
    {
      universalIdentifier: SPECIAL_DAY_DATE_FIELD_UID,
      type: FieldType.TEXT,
      name: 'date',
      label: 'Date',
      description: 'YYYY-MM-DD, used when kind is Specific date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: SPECIAL_DAY_MULTIPLIER_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'multiplier',
      label: 'Multiplier',
      description: 'Pay multiplier, e.g. 2 = 200%',
      icon: 'IconPercentage',
      isNullable: false,
      defaultValue: 2,
    },
    {
      universalIdentifier: SPECIAL_DAY_IS_ACTIVE_FIELD_UID,
      type: FieldType.BOOLEAN,
      name: 'isActive',
      label: 'Active',
      description: 'Inactive special days are ignored',
      icon: 'IconToggleRight',
      isNullable: false,
      defaultValue: true,
    },
  ],
});
