import { defineView, ViewType } from 'twenty-sdk/define';

import {
  ALL_SHIFTS_VIEW_CHECK_IN_AT_FIELD_UID,
  ALL_SHIFTS_VIEW_CHECK_IN_LATE_MINUTES_FIELD_UID,
  ALL_SHIFTS_VIEW_CHECK_OUT_AT_FIELD_UID,
  ALL_SHIFTS_VIEW_DATE_FIELD_UID,
  ALL_SHIFTS_VIEW_MEMBER_FIELD_UID,
  ALL_SHIFTS_VIEW_NAME_FIELD_UID,
  ALL_SHIFTS_VIEW_STATUS_FIELD_UID,
  ALL_SHIFTS_VIEW_TEMPLATE_CODE_FIELD_UID,
  ALL_SHIFTS_VIEW_UID,
  ALL_SHIFTS_VIEW_WORKING_MINUTES_FIELD_UID,
  MEMBER_ON_SHIFT_FIELD_UID,
  SHIFT_CHECK_IN_AT_FIELD_UID,
  SHIFT_CHECK_IN_LATE_MINUTES_FIELD_UID,
  SHIFT_CHECK_OUT_AT_FIELD_UID,
  SHIFT_DATE_FIELD_UID,
  SHIFT_NAME_FIELD_UID,
  SHIFT_OBJECT_UID,
  SHIFT_STATUS_FIELD_UID,
  SHIFT_TEMPLATE_CODE_SNAPSHOT_FIELD_UID,
  SHIFT_WORKING_MINUTES_FIELD_UID,
} from '../constants/universal-identifiers';

export default defineView({
  universalIdentifier: ALL_SHIFTS_VIEW_UID,
  name: 'All Shifts',
  objectUniversalIdentifier: SHIFT_OBJECT_UID,
  type: ViewType.TABLE,
  icon: 'IconCalendarClock',
  position: 0,
  fields: [
    {
      universalIdentifier: ALL_SHIFTS_VIEW_NAME_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_NAME_FIELD_UID,
      position: 0,
      isVisible: true,
      size: 180,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_DATE_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_DATE_FIELD_UID,
      position: 1,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_STATUS_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_STATUS_FIELD_UID,
      position: 2,
      isVisible: true,
      size: 130,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_MEMBER_FIELD_UID,
      fieldMetadataUniversalIdentifier: MEMBER_ON_SHIFT_FIELD_UID,
      position: 3,
      isVisible: true,
      size: 180,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_TEMPLATE_CODE_FIELD_UID,
      fieldMetadataUniversalIdentifier:
        SHIFT_TEMPLATE_CODE_SNAPSHOT_FIELD_UID,
      position: 4,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_CHECK_IN_AT_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_CHECK_IN_AT_FIELD_UID,
      position: 5,
      isVisible: true,
      size: 160,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_CHECK_OUT_AT_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_CHECK_OUT_AT_FIELD_UID,
      position: 6,
      isVisible: true,
      size: 160,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_CHECK_IN_LATE_MINUTES_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_CHECK_IN_LATE_MINUTES_FIELD_UID,
      position: 7,
      isVisible: true,
      size: 150,
    },
    {
      universalIdentifier: ALL_SHIFTS_VIEW_WORKING_MINUTES_FIELD_UID,
      fieldMetadataUniversalIdentifier: SHIFT_WORKING_MINUTES_FIELD_UID,
      position: 8,
      isVisible: true,
      size: 140,
    },
  ],
});
