import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  DEVELOPMENT_DELIVERY_OBJECT_UID,
  DEVELOPMENT_DELIVERY_DELIVERY_TYPE_FIELD_UID,
  DEVELOPMENT_DELIVERY_EXTERNAL_ID_FIELD_UID,
  DEVELOPMENT_DELIVERY_EVENT_ID_FIELD_UID,
  DEVELOPMENT_DELIVERY_TITLE_FIELD_UID,
  DEVELOPMENT_DELIVERY_STATUS_FIELD_UID,
  DEVELOPMENT_DELIVERY_COMMIT_SHA_FIELD_UID,
  DEVELOPMENT_DELIVERY_BRANCH_NAME_FIELD_UID,
  DEVELOPMENT_DELIVERY_PIPELINE_ID_FIELD_UID,
  DEVELOPMENT_DELIVERY_ENVIRONMENT_NAME_FIELD_UID,
  DEVELOPMENT_DELIVERY_ENVIRONMENT_TYPE_FIELD_UID,
  DEVELOPMENT_DELIVERY_OCCURRED_AT_FIELD_UID,
  DEVELOPMENT_DELIVERY_STARTED_AT_FIELD_UID,
  DEVELOPMENT_DELIVERY_URL_FIELD_UID,
} from '../constants/universal-identifiers';

// Immutable status events retain provider ordering across retries and late deliveries.
export default defineObject({
  universalIdentifier: DEVELOPMENT_DELIVERY_OBJECT_UID,
  nameSingular: 'developmentDelivery',
  namePlural: 'developmentDeliveries',
  labelSingular: 'Development delivery',
  labelPlural: 'Development deliveries',
  description: 'Build and deployment status history linked to an issue',
  icon: 'IconSettingsAutomation',
  labelIdentifierFieldMetadataUniversalIdentifier:
    DEVELOPMENT_DELIVERY_TITLE_FIELD_UID,
  fields: [
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_DELIVERY_TYPE_FIELD_UID,
      name: 'deliveryType',
      label: 'Type',
      type: FieldType.SELECT,
      icon: 'IconSettingsAutomation',
      isNullable: true,
      isUIEditable: false,
      options: [
        {
          id: '0a878f9a-463d-47ed-aeab-e5d14a263d55',
          value: 'BUILD',
          label: 'Build',
          position: 0,
          color: 'blue',
        },
        {
          id: '8180329c-63c8-48c2-a9b4-9ca8071e9d5e',
          value: 'DEPLOYMENT',
          label: 'Deployment',
          position: 1,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_EXTERNAL_ID_FIELD_UID,
      name: 'externalId',
      label: 'External id',
      type: FieldType.TEXT,
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_EVENT_ID_FIELD_UID,
      name: 'eventId',
      label: 'Event id',
      type: FieldType.TEXT,
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_TITLE_FIELD_UID,
      name: 'title',
      label: 'Title',
      type: FieldType.TEXT,
      icon: 'IconNotes',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_STATUS_FIELD_UID,
      name: 'status',
      label: 'Status',
      type: FieldType.TEXT,
      icon: 'IconCircleCheck',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_COMMIT_SHA_FIELD_UID,
      name: 'commitSha',
      label: 'Commit SHA',
      type: FieldType.TEXT,
      icon: 'IconGitCommit',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_BRANCH_NAME_FIELD_UID,
      name: 'branchName',
      label: 'Branch',
      type: FieldType.TEXT,
      icon: 'IconGitBranch',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_PIPELINE_ID_FIELD_UID,
      name: 'pipelineId',
      label: 'Pipeline',
      type: FieldType.TEXT,
      icon: 'IconSettingsAutomation',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_ENVIRONMENT_NAME_FIELD_UID,
      name: 'environmentName',
      label: 'Environment',
      type: FieldType.TEXT,
      icon: 'IconCloud',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_ENVIRONMENT_TYPE_FIELD_UID,
      name: 'environmentType',
      label: 'Environment type',
      type: FieldType.TEXT,
      icon: 'IconCloud',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_OCCURRED_AT_FIELD_UID,
      name: 'occurredAt',
      label: 'Updated at provider',
      type: FieldType.DATE_TIME,
      icon: 'IconClock',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_STARTED_AT_FIELD_UID,
      name: 'startedAt',
      label: 'Started at',
      type: FieldType.DATE_TIME,
      icon: 'IconClock',
      isNullable: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: DEVELOPMENT_DELIVERY_URL_FIELD_UID,
      name: 'url',
      label: 'Log URL',
      type: FieldType.TEXT,
      icon: 'IconLink',
      isNullable: true,
      isUIEditable: false,
    },
  ],
});
