import { defineObject, FieldType } from 'twenty-sdk/define';

import { ISSUE_ATTACHMENTS_MAX_VALUES } from '../constants/issue-attachments';
import { ISSUE_LABEL_OPTIONS } from '../constants/issue-label-options';
import { ISSUE_PRIORITY_OPTIONS } from '../constants/issue-priority-options';
import { ISSUE_RESOLUTION_OPTIONS } from '../constants/issue-resolution-options';
import { ISSUE_TYPE_OPTIONS } from '../constants/issue-type-options';
import {
  ISSUE_ATTACHMENTS_FIELD_UID,
  ISSUE_DESCRIPTION_FIELD_UID,
  ISSUE_DUE_DATE_FIELD_UID,
  ISSUE_KEY_FIELD_UID,
  ISSUE_LABELS_FIELD_UID,
  ISSUE_OBJECT_UID,
  ISSUE_ORIGINAL_ESTIMATE_MINUTES_FIELD_UID,
  ISSUE_PRIORITY_FIELD_UID,
  ISSUE_REMAINING_ESTIMATE_MINUTES_FIELD_UID,
  ISSUE_RESOLUTION_FIELD_UID,
  ISSUE_STORY_POINTS_FIELD_UID,
  ISSUE_TIME_SPENT_MINUTES_FIELD_UID,
  ISSUE_TITLE_FIELD_UID,
  ISSUE_TYPE_FIELD_UID,
} from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: ISSUE_OBJECT_UID,
  nameSingular: 'issue',
  namePlural: 'issues',
  labelSingular: 'Issue',
  labelPlural: 'Issues',
  description: 'An issue',
  icon: 'IconLayoutKanban',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: ISSUE_TITLE_FIELD_UID,
  fields: [
    {
      universalIdentifier: ISSUE_TITLE_FIELD_UID,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      description: 'Issue title',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_KEY_FIELD_UID,
      type: FieldType.TEXT,
      name: 'issueKey',
      label: 'Key',
      description: 'Issue key, auto-generated from the project key',
      icon: 'IconKey',
      isNullable: true,
      isUnique: true,
      isUIEditable: false,
      isSearchable: true,
    },
    {
      universalIdentifier: ISSUE_DESCRIPTION_FIELD_UID,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Description',
      description: 'Issue description',
      icon: 'IconFilePencil',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_TYPE_FIELD_UID,
      type: FieldType.SELECT,
      name: 'issueType',
      label: 'Issue type',
      description: 'Issue type',
      icon: 'IconTag',
      isNullable: true,
      defaultValue: "'TASK'",
      options: [...ISSUE_TYPE_OPTIONS],
    },
    {
      universalIdentifier: ISSUE_PRIORITY_FIELD_UID,
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      description: 'Issue priority',
      icon: 'IconFlag',
      isNullable: true,
      defaultValue: "'MEDIUM'",
      options: [...ISSUE_PRIORITY_OPTIONS],
    },
    {
      universalIdentifier: ISSUE_RESOLUTION_FIELD_UID,
      type: FieldType.SELECT,
      name: 'resolution',
      label: 'Resolution',
      description: 'Issue resolution',
      icon: 'IconCircleCheck',
      isNullable: true,
      options: [...ISSUE_RESOLUTION_OPTIONS],
    },
    {
      universalIdentifier: ISSUE_STORY_POINTS_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'storyPoints',
      label: 'Story points',
      description: 'Story points estimate',
      icon: 'IconNumber',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_LABELS_FIELD_UID,
      type: FieldType.MULTI_SELECT,
      name: 'labels',
      label: 'Labels',
      description: 'Issue labels',
      icon: 'IconTags',
      isNullable: true,
      options: [...ISSUE_LABEL_OPTIONS],
    },
    {
      universalIdentifier: ISSUE_DUE_DATE_FIELD_UID,
      type: FieldType.DATE_TIME,
      name: 'dueDate',
      label: 'Due date',
      description: 'Issue due date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_ORIGINAL_ESTIMATE_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'originalEstimateMinutes',
      label: 'Original estimate (minutes)',
      description: 'Original time estimate in minutes',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_REMAINING_ESTIMATE_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'remainingEstimateMinutes',
      label: 'Remaining estimate (minutes)',
      description: 'Remaining time estimate in minutes',
      icon: 'IconClockHour4',
      isNullable: true,
    },
    {
      universalIdentifier: ISSUE_TIME_SPENT_MINUTES_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'timeSpentMinutes',
      label: 'Time spent (minutes)',
      description: 'Total time logged in minutes',
      icon: 'IconClockPlay',
      isNullable: true,
    },
    // The only way a file from a user's disk can reach this workspace. The
    // host renders this field inside the FIELDS widget with its own native
    // picker, so the browser holds the file and the host uploads it — none of
    // it crosses the front component sandbox, which cannot receive file bytes
    // at all. It doubles as the upload target the markdown composer names when
    // it stores a pasted image URL.
    {
      universalIdentifier: ISSUE_ATTACHMENTS_FIELD_UID,
      type: FieldType.FILES,
      name: 'attachments',
      label: 'Attachments',
      description: 'Files attached to this issue',
      icon: 'IconPaperclip',
      isNullable: true,
      universalSettings: { maxNumberOfValues: ISSUE_ATTACHMENTS_MAX_VALUES },
    },
  ],
});
